// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }




import { Metadata } from 'next'
import { Inter, DynaPuff } from 'next/font/google'
import './globals.css'

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const dynaPuff = DynaPuff({
  subsets: ['latin'],
  variable: '--font-dynapuff',
  display: 'swap',
  weight: '400', // This ensures regular weight
})

export const metadata = {
  title: 'Lyfe Travels - Your Journey Begins Here',
  description: 'Discover amazing travel packages with Lyfe Travels',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${dynaPuff.variable}`}>
      <body className="font-sans">
        {children}
      </body>
    </html>
  )
}